### ISSUE TITLE
Input 8 not selectable

### ISSUE THREAD

**Issue by peskdale** [YSTV/BMDSwitcherApps#2]
On ATEM 1M/E (old one) switching program to input 8 is recognised in the messages box, but the mapping does not turn red, nor does the mapped tally cube light.

No idea if this affects the new one or not.

**Comment by peskdale** [comment]
https://github.com/YSTV/BMDSwitcherApps/blob/tally-eight-channels/TallyControl/SwitcherPanel.cs#L254

pnlChannelDropDowns.Controls.Count = 8, and this is one-indexed

**Comment by peskdale** [comment]
Verified working. Ready to be pulled.

**Comment by samdbmg** [comment]
PR opened (sorry, missed the mail)

**Comment by peskdale** [comment]
Merged.
